version: '3.8'

services:
  # Next.js Frontend
  frontend:
    build:
      context: ./dashboard-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - cartorio-network

  # Scraper Worker
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - GBP_SEARCH_URL=${GBP_SEARCH_URL}
      - CRON_SCHEDULE=${CRON_SCHEDULE:-0 */1 * * *}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - PORT=3001
    volumes:
      - scraper-logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - cartorio-network
    depends_on:
      - frontend

volumes:
  scraper-logs:

networks:
  cartorio-network:
    driver: bridge
